config/routes.rb
Rails.application.routes.draw do

  root "root#home"

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  get '/log_out', to: 'sessions#destroy', as: :log_out

  #admin dashboard
  namespace :admin, path: 'admin' do
    root to: 'users#show'
    resources :users, :posts, :guestbook_entries, :locations, :equipment_items, :gallery_images

    #nested Routes for Seminars
    resources :seminar_types do
      resources :seminar_instances do
        resources :seminar_images
        resources :seminar_contents
        resources :seminars do
          get '/send_mail', to: 'seminars#send_mail'
          resources :bookings
        end
      end
    end
  end

  #for users
  namespace :frontend, path: '/' do
    root to: "root#home"

    #user handeling
    resources :users
    get '/sign_up', to: 'users#new', as: :sign_up

    #static pages
    get "/ueber-ines", to: "pages#ines"
    get "/ueber-wildnisschule-wurzelholz", to: "pages#wurzelholz"
    get "/seminar-infos", to: "pages#seminar_infos"
    get "/impressum", to: "pages#impressum"
    get "/datenschutz", to: "pages#datenschutz"
    get "/agb", to: "pages#agb"

    #flat models
    resources :galleries, only: [:index], path: 'gallerie'
    resources :locations, only: [:show], path: 'orte'
    resources :posts, only: [:show, :index], path: 'blog'
    resources :guestbook_entries, path: 'gästebuch'

    #nested Routes for Seminars
    resources :seminar_types, only: :index, path: 'angebot'
    resources :seminar_types, path: '', except: [:index] do

      resources :seminar_instances, only: [:index], path: 'veranstaltungen'
      resources :seminar_instances, path: '', except: [:index] do

        resources :seminars, path: '', except: :index do
          get '/account_abfrage', to: 'bookings#account_abfrage'
          resources :bookings, path: 'buchung' do
            get '/erfolgreich', to: 'bookings#success'
            get '/confirmation', to: 'bookings#confirmation'
            #stripe
            post '/stripe_checkout', to: 'stripe#create'
            get '/stripe_sucess', to: 'stripe#sucess'
            get '/stripe_failure', to: 'stripe#failure'
            #paypal
            post :create_order, to: 'paypal#create_order'
            post :capture_order, to: 'paypal#capture_order'
          end
        end
      end
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :seminars

  has_one_attached :location_image

  validates :location_image, :name, :description, :latitude, :longitude, presence: true

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.city = geo.city
      obj.zip = geo.postal_code
      obj.street = geo.street
      obj.house_number = geo.house_number
    end
  end

  after_validation :reverse_geocode

  def location
    city = geo.city
    zipcode = geo.postal_code
    street = geo.street
    house_number  = geo.house_number
  end
end

app/controllers/admin/locations_controller.rb
module Admin
  class LocationsController < Admin::BaseController

    before_action :set_location, only: %i[edit update show]

    def index
      @locations = Location.all
    end

    def new
      @location = Location.new
    end

    def create
      @location = Location.new(location_params)
      if @location.save
        flash[:notice] = "Du hast erfolgreich einen neuen Ort erstellt :)"
        redirect_to admin_location_path(@location)
      else
        flash[:alert] = "Da ist etwas schief gelaufen :/"
        render :new, status: :unporcessable_eintity
      end
    end

    def edit
    end

    def update
      if @location.update(location_params)
        flash[:notice] = "Du hast " + @location.name +  " erfolgreich editiert :)"
        redirect_to admin_location_path(@location)
      else
        flash[:alert] = "Da ist etwas schief gelaufen :/"
        render :edit, status: :unporcessable_eintity
      end
    end

  private

    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:description, :name, :latitude, :longitude, :adress, :location_image)
    end

  end
end

app/controllers/frontend/locations_controller.rb
module Frontend
  class LocationsController < ApplicationController
    load_and_authorize_resource

    before_action :set_location, only: %i[show]

    def show
    end

  private

    def set_location
      @location = Location.find(params[:id])
    end

  end
end

app/views/admin/locations/_form.html.erb
<% if @location.persisted? %>
  <% @url = admin_location_path(@location.id) %>
<% else %>
  <% @url = admin_locations_path %>
<% end %>

<%= form_for [@location], url: @url do |f| %>
  <div class="form-container">
    <%= render 'shared/errors', obj: @location %>

    <div class="form-container__group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
    </div>

    <div class="form-container__group">
      <%= f.label :description, "Beschreibung" %>
      <%= f.text_area :description %>
    </div>

    <div class="form-container__group">
      <%= f.label :latitude %>
      <%= f.number_field :latitude, step: :any %>
    </div>

    <div class="form-container__group">
      <%= f.label :longitude %>
      <%= f.number_field :longitude, step: :any %>
    </div>

    <div class="form-container__group">
      <%= f.label :location_image, "Bild" %>
      <%= f.file_field :location_image %>
    </div>

    <%= f.submit "save", class: "button button-primary" %>
  </div>
<% end %>

app/views/admin/locations/edit.html.erb
<h1><%= @location.name %> editieren</h1>

<%= render 'form' %>

app/views/admin/locations/index.html.erb
<h1>Seminar Orte</h1>
<% @locations.each do |s| %>
  <h2><%= s.name %></h2>
  <%= link_to "Editieren", edit_admin_location_path(s.id), class: "button button-secondary " %>
  <%= link_to s.name + " anschauen", admin_location_path(s.id), class: "button button-primary " %>
<% end %>
<hr class="mt-xs">
<br>
<%= link_to "Neuen Seminar-Ort erstellen", new_admin_location_path, class: "button button-primary mt-xs" %>

app/views/admin/locations/new.html.erb
<h1>Neuen Seminarort erstellen</h1>
<%= render 'form' %>

app/views/admin/locations/show.html.erb
<h1><%= @location.name %></h1>
<p><%= @location.description %></p>
<%= image_tag(@location.location_image, style: "width:400px;", alt: "Bild des Seminarorts der Wildnisschule Wurzelholz") %>
<br>

<%= link_to 'Editieren', edit_admin_location_path(@location), class: "button button-secondary" %>