config/routes.rb
Rails.application.routes.draw do

  root "root#home"

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  get '/log_out', to: 'sessions#destroy', as: :log_out

  #admin dashboard
  namespace :admin, path: 'admin' do
    root to: 'users#show'
    resources :users, :posts, :guestbook_entries, :locations, :equipment_items, :gallery_images

    #nested Routes for Seminars
    resources :seminar_types do
      resources :seminar_instances do
        resources :seminar_images
        resources :seminar_contents
        resources :seminars do
          get '/send_mail', to: 'seminars#send_mail'
          resources :bookings
        end
      end
    end
  end

  #for users
  namespace :frontend, path: '/' do
    root to: "root#home"

    #user handeling
    resources :users
    get '/sign_up', to: 'users#new', as: :sign_up

    #static pages
    get "/ueber-ines", to: "pages#ines"
    get "/ueber-wildnisschule-wurzelholz", to: "pages#wurzelholz"
    get "/seminar-infos", to: "pages#seminar_infos"
    get "/impressum", to: "pages#impressum"
    get "/datenschutz", to: "pages#datenschutz"
    get "/agb", to: "pages#agb"

    #flat models
    resources :galleries, only: [:index], path: 'gallerie'
    resources :locations, only: [:show], path: 'orte'
    resources :posts, only: [:show, :index], path: 'blog'
    resources :guestbook_entries, path: 'gästebuch'

    #nested Routes for Seminars
    resources :seminar_types, only: :index, path: 'angebot'
    resources :seminar_types, path: '', except: [:index] do

      resources :seminar_instances, only: [:index], path: 'veranstaltungen'
      resources :seminar_instances, path: '', except: [:index] do

        resources :seminars, path: '', except: :index do
          get '/account_abfrage', to: 'bookings#account_abfrage'
          resources :bookings, path: 'buchung' do
            get '/erfolgreich', to: 'bookings#success'
            get '/confirmation', to: 'bookings#confirmation'
            #stripe
            post '/stripe_checkout', to: 'stripe#create'
            get '/stripe_sucess', to: 'stripe#sucess'
            get '/stripe_failure', to: 'stripe#failure'
            #paypal
            post :create_order, to: 'paypal#create_order'
            post :capture_order, to: 'paypal#capture_order'
          end
        end
      end
    end
  end
end

app/views/layouts/admin/_footer.html.erb
<div class="footer-container">
  <ul>
    <li>
      <%= link_to 'Impressum', frontend_impressum_path  %>
    </li>
    <li>
      <%= link_to 'Datenschutz', frontend_datenschutz_path  %>
    </li>
    <li>
      <%= link_to 'AGB', frontend_agb_path  %>
    </li>
  </ul>
</div>

app/views/layouts/admin/_navigation.html.erb
<nav class="navigation-container navigation_container__preload" data-controller="navigation" aria-label="website">

  <button class="navigation-container__burger-button" aria-label="Toggle navigation" data-navigation-target="burgerButton" data-action="navigation#toggleMenu"  aria-controls="nav-items" aria-expanded="false">
    <div aria-hidden="true"></div>
    <div aria-hidden="true"></div>
    <div aria-hidden="true"></div>
  </button>

  <ul class="navigation-container__navigation">

    <li  class="navigation-container__dropdown-toggle">
      <%= link_to "Seminare", admin_seminar_types_path, "data-navigation-target": "navItem"  %>
      <ul class="sub-menu">
        <% SeminarType.all.each do |s| %>
          <li><%= link_to s.name, admin_seminar_type_seminar_instances_path(s.id), "data-navigation-target": "navItem"  %></li>
        <% end %>
      </ul>
    </li>

    <li  class="navigation-container__dropdown-toggle">
      Addons
      <ul class="sub-menu">
        <li><%= link_to "Orte", admin_locations_path, "data-navigation-target": "navItem"  %></li>
        <li><%= link_to "Ausrüstung", admin_equipment_items_path, "data-navigation-target": "navItem"  %></li>
      </ul>
    </li>

    <li  class="navigation-container__dropdown-toggle">
      Allgemein
      <ul class="sub-menu">
        <li><%= link_to "Blog", admin_posts_path, "data-navigation-target": "navItem"  %></li>
        <li><%= link_to "Gästebuch", admin_guestbook_entries_path, "data-navigation-target": "navItem"  %></li>
        <li><%= link_to "Gallerie", admin_gallery_images_path, "data-navigation-target": "navItem"  %></li>
      </ul>
    </li>

    <li class="navigation-container__dropdown-toggle">
      <b>Admin</b>
      <ul class="sub-menu">
        <li><%= link_to "Dashboard", frontend_user_path(current_user), "data-navigation-target": "navItem"  %></li>
        <li><%= link_to "Log out", log_out_path, "data-navigation-target": "navItem" %></li>
      </ul>
    </li>

  </ul>
</nav>