config/routes.rb
Rails.application.routes.draw do

  root "root#home"

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  get '/log_out', to: 'sessions#destroy', as: :log_out

  #admin dashboard
  namespace :admin, path: 'admin' do
    root to: 'users#show'
    resources :users, :posts, :guestbook_entries, :locations, :equipment_items, :gallery_images

    #nested Routes for Seminars
    resources :seminar_types do
      resources :seminar_instances do
        resources :seminar_images
        resources :seminar_contents
        resources :seminars do
          get '/send_mail', to: 'seminars#send_mail'
          resources :bookings
        end
      end
    end
  end

  #for users
  namespace :frontend, path: '/' do
    root to: "root#home"

    #user handeling
    resources :users
    get '/sign_up', to: 'users#new', as: :sign_up

    #static pages
    get "/ueber-ines", to: "pages#ines"
    get "/ueber-wildnisschule-wurzelholz", to: "pages#wurzelholz"
    get "/seminar-infos", to: "pages#seminar_infos"
    get "/impressum", to: "pages#impressum"
    get "/datenschutz", to: "pages#datenschutz"
    get "/agb", to: "pages#agb"

    #flat models
    resources :galleries, only: [:index], path: 'gallerie'
    resources :locations, only: [:show], path: 'orte'
    resources :posts, only: [:show, :index], path: 'blog'
    resources :guestbook_entries, path: 'gästebuch'

    #nested Routes for Seminars
    resources :seminar_types, only: :index, path: 'angebot'
    resources :seminar_types, path: '', except: [:index] do

      resources :seminar_instances, only: [:index], path: 'veranstaltungen'
      resources :seminar_instances, path: '', except: [:index] do

        resources :seminars, path: '', except: :index do
          get '/account_abfrage', to: 'bookings#account_abfrage'
          resources :bookings, path: 'buchung' do
            get '/erfolgreich', to: 'bookings#success'
            get '/confirmation', to: 'bookings#confirmation'
            #stripe
            post '/stripe_checkout', to: 'stripe#create'
            get '/stripe_sucess', to: 'stripe#sucess'
            get '/stripe_failure', to: 'stripe#failure'
            #paypal
            post :create_order, to: 'paypal#create_order'
            post :capture_order, to: 'paypal#capture_order'
          end
        end
      end
    end
  end
end

app/models/guestbook_entry.rb
class GuestbookEntry < ApplicationRecord
  belongs_to :user, optional: :true
  belongs_to :seminar_instance, optional: true

  validates :title, :content, presence: true
end

app/controllers/admin/guestbook_entries_controller.rb
module Admin
  class GuestbookEntriesController < Admin::BaseController
    load_and_authorize_resource

    def index
      @guestbook_entries = GuestbookEntry.paginate(page: params[:page], per_page: 3)
    end

    def new
      @guestbook_entry = GuestbookEntry.new
    end

    def create
      @guestbook_entry = GuestbookEntry.new(guestbook_entry_params)
      if @guestbook_entry.save
        flash[:notice] = "Dein Gästebucheintrag wurde erfolgreich erstellt :)"
        redirect_to admin_guestbook_entries_path
      else
        render 'new'
      end
    end

    def destroy
      @guestbook_entry.destroy
      flash[:notice] = "Du hast den Gästebucheintrag erfolgreich gelöscht :)"
      redirect_to admin_guestbook_entries_path
    end

  private

    def guestbook_entry_params
      params.require(:guestbook_entry).permit(:seminar_instance_id, :content, :title, :author).merge(user: current_user)
    end

  end
end

app/controllers/frontend/guestbook_entries_controller.rb
module Frontend
  class GuestbookEntriesController < ApplicationController
    load_and_authorize_resource

    def index
      @guestbook_entries = GuestbookEntry.paginate(page: params[:page], per_page: 3)
    end

    def new
      @guestbook_entry = GuestbookEntry.new
    end

    def create
      @guestbook_entry = GuestbookEntry.new(guestbook_entry_params)
      if @guestbook_entry.save
        flash[:notice] = "Dein Gästebucheintrag wurde erfolgreich erstellt :)"
        redirect_to frontend_guestbook_entries_path
      else

        render 'new'
      end
    end

  private

    def guestbook_entry_params
      params.require(:guestbook_entry).permit(:seminar_instance_id, :content, :title).merge(user: current_user)
    end

  end
end

app/views/admin/guestbook_entries/_form.html.erb
<%= form_for [@guestbook_entry], url: admin_guestbook_entries_path(@guestbook_entry.id) do |f| %>
  <div class="form-container">
    <%= render 'shared/errors', obj: @guestbook_entry %>

    <%= fields_for :guestbook_entry do |ab| %>
      <div class="form-container__group">
        <%= ab.label "Für welches Seminar möchtest du deinen Eintrag schreiben?" %>
        <br>
        <%= ab.select :seminar_instance_id, SeminarInstance.all.map { |s| [s.name, s.id] } %>
      </div>
    <% end %>

    <div class="form-container__group">
      <%= f.label :author %>
      <%= f.text_field :author %>
    </div>

    <div class="form-container__group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="form-container__group">
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>

    <%= f.submit "absenden", class: "button button-primary"%>
  </div>

<% end %>

app/views/admin/guestbook_entries/index.html.erb
<div class="guestbook" data-controller="confirmation">
  <h1>Gästebuch</h1>

  <div class="pagination">
    <%= page_entries_info @guestbook_entries %>
    <%= will_paginate @guestbook_entries %>
  </div>

  <% @guestbook_entries.each do |g| %>
    <div class="guestbook-entry">
      <div class="guestbook-entry__header">
        <p>
          <% if g.author %>
            <%= g.author %>
          <% else %>
            <%= g.user.first_name %>
          <% end %>
          -
          <%= g.created_at.strftime("%d.%m.%Y") %>
          <% if g.seminar_instance %>
            - <%= g.seminar_instance.name %>
          <% end %>
        </p>
      </div>

      <h2 class="guestbook-entry__title" ><%= g.title %></h2>
      <p class="guestbook-entry__content"><%= g.content %></p>
      <%= link_to 'Entfernen', admin_guestbook_entry_path(g.id, action: :destroy), method: :delete, data: { action:  "click->confirmation#delete" } %>
    </div>
  <% end %>

  <div class="pagination mt-xs">
    <%= page_entries_info @guestbook_entries %>
    <%= will_paginate @guestbook_entries %>
  </div>

  <div class="button-container">
    <%= link_to "Neuen Eintrag erstellen", new_admin_guestbook_entry_path, class: "button button-primary" %>
  </div>
</div>

app/views/admin/guestbook_entries/new.html.erb
<h1>Schreibe einen Gästebucheintrag :)</h1>
<% if current_user %>
  <%= render "form" %>
<% else %>
  <p>Bitte log dich ein um einen Eintrag zu schreiben. Falls du keinen Account erstellen möchtest, schick deinen Eintrag einfach an <a href="mailto:inescollmer@web.de">inescollmer@web.de</a> und ich trage ihn für dich ein.</p>
  <%= link_to "Log in", log_in_path, class: "button button-primary" %>
<% end %>