config/routes.rb
Rails.application.routes.draw do

  root "root#home"

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  get '/log_out', to: 'sessions#destroy', as: :log_out

  #admin dashboard
  namespace :admin, path: 'admin' do
    root to: 'users#show'
    resources :users, :posts, :guestbook_entries, :locations, :equipment_items, :gallery_images

    #nested Routes for Seminars
    resources :seminar_types do
      resources :seminar_instances do
        resources :seminar_images
        resources :seminar_contents
        resources :seminars do
          get '/send_mail', to: 'seminars#send_mail'
          resources :bookings
        end
      end
    end
  end

  #for users
  namespace :frontend, path: '/' do
    root to: "root#home"

    #user handeling
    resources :users
    get '/sign_up', to: 'users#new', as: :sign_up

    #static pages
    get "/ueber-ines", to: "pages#ines"
    get "/ueber-wildnisschule-wurzelholz", to: "pages#wurzelholz"
    get "/seminar-infos", to: "pages#seminar_infos"
    get "/impressum", to: "pages#impressum"
    get "/datenschutz", to: "pages#datenschutz"
    get "/agb", to: "pages#agb"

    #flat models
    resources :galleries, only: [:index], path: 'gallerie'
    resources :locations, only: [:show], path: 'orte'
    resources :posts, only: [:show, :index], path: 'blog'
    resources :guestbook_entries, path: 'gästebuch'

    #nested Routes for Seminars
    resources :seminar_types, only: :index, path: 'angebot'
    resources :seminar_types, path: '', except: [:index] do

      resources :seminar_instances, only: [:index], path: 'veranstaltungen'
      resources :seminar_instances, path: '', except: [:index] do

        resources :seminars, path: '', except: :index do
          get '/account_abfrage', to: 'bookings#account_abfrage'
          resources :bookings, path: 'buchung' do
            get '/erfolgreich', to: 'bookings#success'
            get '/confirmation', to: 'bookings#confirmation'
            #stripe
            post '/stripe_checkout', to: 'stripe#create'
            get '/stripe_sucess', to: 'stripe#sucess'
            get '/stripe_failure', to: 'stripe#failure'
            #paypal
            post :create_order, to: 'paypal#create_order'
            post :capture_order, to: 'paypal#capture_order'
          end
        end
      end
    end
  end
end

app/models/seminar_instance.rb
class SeminarInstance < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  monetize :price_cents

  belongs_to :seminar_type

  has_many :equipment_lists
  has_many :equipment_items, through: :equipment_lists
  has_many :seminars
  has_many :guestbook_entries
  has_many :seminar_contents

  has_one_attached :image_1
  has_one_attached :image_2

  validates :name, :description, :price_cents, :image_1, :image_2, :breakfast, :lunch, :dinner, presence: true

  accepts_nested_attributes_for :seminar_contents, allow_destroy: true
end

app/controllers/admin/seminar_instances_controller.rb
module Admin
  class SeminarInstancesController < Admin::BaseController
    load_and_authorize_resource

    before_action :set_seminar_instance, only: %i[show edit update]
    before_action :set_seminar_type, only: %i[show index new create edit update]
    before_action :set_seminars, only: %i[show]

    def show
    end

    def index
      @seminar_instances = SeminarInstance.where(seminar_type: @seminar_type)
    end

    def new
      @seminar_instance = SeminarInstance.new
      @seminar_instance.seminar_contents.build
    end

    def create
      @seminar_instance = SeminarInstance.new(seminar_instance_params)
      if @seminar_instance.save
        redirect_to admin_seminar_type_seminar_instances_path, notice: "Du hast erfolgreich ein neues Seminar erstellt!"
      else
        render :new, alert: "Da ist leider etwas schief gelaufen :/"
      end
    end

    def edit
    end

    def update
      if @seminar_instance.update(seminar_instance_params)
        redirect_to admin_seminar_type_seminar_instance_path, notice: "Du hast das Seminar erfolgreich editiert"
      else
        render :edit, status: :unprocessable_entity
      end
    end

  private

    def seminar_instance_params
      params.require(:seminar_instance).permit(:name, :description, :price_cents, :image_1, :image_2, :breakfast, :lunch, :dinner, equipment_item_ids: [],  seminar_contents_attributes: [:id, :content]).merge(seminar_type: @seminar_type).permit!
    end

    def set_seminar_instance
      @seminar_instance = SeminarInstance.find(params[:id])
    end

    def set_seminar_type
      @seminar_type = SeminarType.find(params[:seminar_type_id])
    end

    def set_seminars
      @seminars = Seminar.where(seminar_instance: @seminar_instance)
    end
  end
end

app/controllers/frontend/seminar_instances_controller.rb
module Frontend
  class SeminarInstancesController < ApplicationController
    before_action :set_seminar_instance, only: %i[show]
    before_action :set_seminar_type, only: %i[show index]
    before_action :set_seminars, only: %i[show]

    def index
      @seminar_instances = SeminarInstance.where(seminar_type: @seminar_type)
    end

    def show
    end

  private

    def set_seminar_instance
      @seminar_instance = SeminarInstance.friendly.find(params[:id])
    end

    def set_seminar_type
      @seminar_type = SeminarType.friendly.find(params[:seminar_type_id])
    end

    def set_seminars
      @seminars = Seminar.where(seminar_instance: @seminar_instance)
    end
  end
end

app/views/admin/seminar_instances/_form.html.erb
<% if @seminar_instance.persisted? %>
  <!-- We are in edit action -->
  <% @url = admin_seminar_type_seminar_instance_path(@seminar_type.id, @seminar_instance.id) %>
<% else %>
  <!-- We are in new -->
  <% @url = admin_seminar_type_seminar_instances_path(@seminar_type.id)  %>
<% end %>

<%= form_for [@seminar_type, @seminar_instance], url: @url do |f| %>
  <div class="form-container" data-controller="confirmation field">
    <%= render 'shared/errors', obj: @seminar_instance %>

    <div class="form-container__group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="form-container__group">
      <%= f.label "Preis in Cent!!", for: :price_cents %>
      <%= f.number_field :price_cents %>
    </div>

    <div class="form-container__group">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <!-- Inhalte -->
    <div class="form-container__group">
      <%= f.label :content, "Inhalte", class: "mt-xs" %>
      <%= f.fields_for :seminar_contents do |content| %>
        <%= content.text_field :content, class: "mt-xs" %>
        <% if @seminar_instance.persisted? %>
          <%= link_to 'Entfernen', admin_seminar_type_seminar_instance_seminar_content_path(@seminar_type.id, @seminar_instance.id, content.object.id, action: :destroy), method: :delete, data: { action:  "click->confirmation#delete" } %>
        <% end %>
      <% end %>
      <div data-field-target="field_container"></div>
      <p class="button button-primary" data-action="click->field#add_field">Neuer Inhalt</p>
    </div>

    <!-- Ausrüstungslist -->
    <div class="form-container__group">
      <%= f.label "Ausrüstungsliste" %>
      <%= f.collection_check_boxes(:equipment_item_ids, EquipmentItem.all, :id, :name, {}, { multiple: true }) do |b| %>
        <div class="form-container__group--multi-select" >
          <%= b.check_box  %>
          <label for="<%= b.text %>">
            <%= b.text %>
          </label>
        </div>
      <% end %>
    </div>

    <div class="form-container__group">
      <%= f.label :breakfast, "Anzahl Frühstück" %>
      <%= f.number_field :breakfast %>
    </div>

    <div class="form-container__group">
      <%= f.label :lunch, "Anzahl Mittagessen" %>
      <%= f.number_field :lunch %>
    </div>

    <div class="form-container__group">
      <%= f.label :dinner, "Anzahl Abendessen" %>
      <%= f.number_field :dinner %>
    </div>

    <div class="form-container__group">
      <%= f.label :image_1 %>
      <%= f.file_field :image_1 %>
    </div>

    <div class="form-container__group">
      <%= f.label :image_2 %>
      <%= f.file_field :image_2 %>
    </div>

    <%= f.submit "save", class: "button button-primary" %>
  </div>
<% end %>

app/views/admin/seminar_instances/edit.html.erb
<h1><%= @seminar_instance.name %> editieren :)</h1>
<%= render 'form' %>

app/views/admin/seminar_instances/index.html.erb
<h1><%= @seminar_type.name %></h1>

<% @seminar_instances.each do |s| %>
  <h2><%= s.name %></h2>
  <%= link_to "Editieren", edit_admin_seminar_type_seminar_instance_path(@seminar_type.id, s.id), class: "button button-secondary"  %>
  <%= link_to "Anschauen", admin_seminar_type_seminar_instance_path(@seminar_type.id, s.id), class: "button button-primary"  %>
<% end %>
<hr class="mt-xs">
<%= link_to "Neue " + @seminar_type.name + " erstellen", new_admin_seminar_type_seminar_instance_path(@seminar_type.id), class: "button button-primary mt-xs" %>

app/views/admin/seminar_instances/new.html.erb
<h1>Neue <%= @seminar_type.name %> erstellen :)</h1>
<%= render 'form' %>

app/views/admin/seminar_instances/show.html.erb
<div class="seminar_instance">
  <h1><%= @seminar_instance.name %></h1>

  <h2>Beschreibung</h2>
  <p><%= @seminar_instance.description %></p>

  <h2>Inhalte:</h2>
  <ul>
    <% @seminar_instance.seminar_contents.each do |s| %>
      <li><%= s.content %></li>
    <% end %>
  </ul>

  <h2>Ausrüstungsliste</h2>
  <ul>
    <% @seminar_instance.equipment_items.each do |i| %>
      <li><%= i.name %></li>
    <% end %>
  </ul>

  <p>Preis: <%= @seminar_instance.price %><%= currency_symbol %></p>

  <h2>Bilder </h2>

  <%= image_tag @seminar_instance.image_1, style: "width:400px; height:300px; object-fit:cover;" %>
  <%= image_tag @seminar_instance.image_2, style: "width:400px; height:300px; object-fit:cover;"  %>
  <br>

  <%= link_to "Seminar Editieren", edit_admin_seminar_type_seminar_instance_path(@seminar_type.id, @seminar_instance.id), class: "button button-secondary" %>

  <h2>Termine:</h2>

  <% @seminars.each do |s| %>
    <p>
      <%= s.start_date.strftime("%d.%m.%Y") %>:
      <%= link_to s.location.name, frontend_location_path(s.location)  %> -
      <%= Booking.where(seminar: s).count %> von
      <%= s.max_participants %> Anmeldungen -
      <%= link_to 'Editieren', edit_admin_seminar_type_seminar_instance_seminar_path(@seminar_type.id, @seminar_instance.id, s.id), class: "red"  %>
    </p>
  <% end %>

  <%= link_to "Neuen Termin anlegen", new_admin_seminar_type_seminar_instance_seminar_path(@seminar_type.id, @seminar_instance.id), class: "button button-secondary" %>
</div>